<div class="xl6 xs6 xm3  text-center item-block margin-large-bottom">
          <div class="item"><a href="[field:typelink /]" title="[field:typename /]" target="_blank">
            <div class="media-img"><span class="chazoomimgs" style="background-image:url(/style/images/s1.jpg)"></span></div>
            <h5>[field:typename /]</h5>
            <p  class="desc"><span>移动共享时代主义</span></p>
            </a></div>
        </div>