<?php
$z[0]=Array("pubdate","",187,233);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",279,328);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%Y-%m\",@me)";
$z[2]=Array("arcurl","",457,472);
$z[2][4]=array();
$z[3]=Array("title","",481,495);
$z[3][4]=array();
$z[4]=Array("title","",497,511);
$z[4][4]=array();
$z[5]=Array("description","",556,606);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,250)";

?>