<?php
$z[0]=Array("global","",272,293);
$z[0][4]=array();
$z[0][4]['name']="cfg_dz";
$z[1]=Array("global","",428,449);
$z[1][4]=array();
$z[1][4]['name']="cfg_dh";
$z[2]=Array("global","",735,756);
$z[2][4]=array();
$z[2][4]['name']="cfg_yx";
$z[3]=Array("global","",774,795);
$z[3][4]=array();
$z[3][4]['name']="cfg_yx";
$z[4]=Array("channel","\r\n          <a href='[field:typeurl/]'>[field:typename/]</a>\r\n          ",995,1116);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[5]=Array("global","",1164,1185);
$z[5][4]=array();
$z[5][4]['name']="cfg_yx";
$z[6]=Array("flink","[field:link /]",1370,1418);
$z[6][4]=array();
$z[6][4]['row']="50";
$z[7]=Array("global","",1759,1780);
$z[7][4]=array();
$z[7][4]['name']="cfg_dh";
$z[8]=Array("global","",1863,1884);
$z[8][4]=array();
$z[8][4]['name']="cfg_dh";
$z[9]=Array("type","<a href=\"[field:typelink /]\"><span class=\"icon-user\"></span>联系</a>",1959,2064);
$z[9][4]=array();
$z[9][4]['typeid']="10";

?>