<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",468,559);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","\r\n                <li><a class=\"first-level\" href='[field:typelink/]'>[field:typename/]</a>\r\n                </li>\r\n                ",624,892);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['currentstyle']="<li class='current'><a href='~typelink~' class='first-level'>~typename~</a></li>";

?>