<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='current'\":@me=\"\";",468,559);
$z[0][4]=array();
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channelartlist","\r\n                <li {dede:field name='currentstyle'/}><a class=\"first-level\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}<span class=\"downward\"></span></a>\r\n                  <ul class=\"drop-menu\">\r\n                    {dede:channel type='son' noself='yes'}\r\n                    <li><a href='[field:typelink/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n                    {/dede:channel}\r\n                  </ul>\r\n                </li>\r\n                ",625,1177);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['typeid']="top";

?>